In [1]:
import pandas as pd

In [2]:
# df_train = pd.read_csv('clean_data_final.csv')

In [3]:
import h2o
from h2o.automl import H2OAutoML
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
; OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
  Starting server from C:\Users\Vibhash-CRM\Anaconda3\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\VIBHAS~1\AppData\Local\Temp\tmpxeow9mtd
  JVM stdout: C:\Users\VIBHAS~1\AppData\Local\Temp\tmpxeow9mtd\h2o_Vibhash_CRM_started_from_python.out
  JVM stderr: C:\Users\VIBHAS~1\AppData\Local\Temp\tmpxeow9mtd\h2o_Vibhash_CRM_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------------
H2O cluster uptime:         03 secs
H2O cluster timezone:       Asia/Kolkata
H2O data parsing timezone:  UTC
H2O cluster version:        3.26.0.3
H2O cluster version age:    8 days
H2O cluster name:           H2O_from_python_Vibhash_CRM_eum2z9
H2O cluster total nodes:    1
H2O cluster free memory:    1.961 Gb
H2O cluster total cores:    8
H2O cluster allowed cores:  8
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Amazon S3, Algos, AutoML, Core V3, Core V4
Python version:             3.7.3 final
--------------------------  ------------------------------------------

In [4]:
train = h2o.import_file('clean_data_final.csv')

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [6]:
imp_col = ["work_interfere","family_history","care_options","Gender","benefits","coworkers","obs_consequence","anonymity","leave"]
x =train.columns
x1=train[imp_col].columns
y = "treatment"
x.remove(y)

In [7]:
train[y] = train[y].asfactor()

In [ ]:
aml = H2OAutoML(max_models=20, seed=1)
aml.train(x=x, y=y, training_frame=train)

AutoML progress: |████████████████████████████████████████████████

In [ ]:
aml_imp = H2OAutoML(max_models=20, seed=1)
aml_imp.train(x=x1, y=y, training_frame=train)

In [8]:
lb = aml.leaderboard
lb.head(rows=lb.nrows)

model_id,auc,logloss,mean_per_class_error,rmse,mse
GBM_grid_1_AutoML_20190901_021154_model_1,0.901287,0.468516,0.166571,0.381534,0.145568
GBM_5_AutoML_20190901_021154,0.89883,0.388066,0.161425,0.350033,0.122523
StackedEnsemble_BestOfFamily_AutoML_20190901_021154,0.898786,0.39536,0.170252,0.353016,0.124621
StackedEnsemble_AllModels_AutoML_20190901_021154,0.897564,0.393193,0.16241,0.350777,0.123044
XRT_1_AutoML_20190901_021154,0.894659,0.404755,0.174189,0.357798,0.128019
GBM_grid_1_AutoML_20190901_021154_model_3,0.894259,0.572388,0.169459,0.436755,0.190755
GLM_grid_1_AutoML_20190901_021154_model_1,0.894059,0.401582,0.175013,0.355958,0.126706
DRF_1_AutoML_20190901_021154,0.893711,0.440267,0.181999,0.360551,0.129997
GBM_4_AutoML_20190901_021154,0.893485,0.415129,0.175653,0.364137,0.132596
GBM_2_AutoML_20190901_021154,0.892054,0.40641,0.165682,0.358764,0.128712
GBM_3_AutoML_20190901_021154,0.889462,0.416363,0.179014,0.363438,0.132087
GBM_1_AutoML_20190901_021154,0.888661,0.423702,0.179966,0.365748,0.133772
GBM_grid_1_AutoML_20190901_021154_model_5,0.88199,0.470967,0.163266,0.38206,0.145969
DeepLearning_grid_1_AutoML_20190901_021154_model_2,0.873048,0.583553,0.183399,0.396213,0.156985
GBM_grid_1_AutoML_20190901_021154_model_2,0.872745,0.661039,0.187208,0.401327,0.161064
DeepLearning_1_AutoML_20190901_021154,0.872707,0.469117,0.185527,0.382358,0.146198
DeepLearning_grid_1_AutoML_20190901_021154_model_5,0.869449,0.512826,0.197883,0.391138,0.152989
DeepLearning_grid_1_AutoML_20190901_021154_model_3,0.865021,0.554908,0.198643,0.39794,0.158356
GBM_grid_1_AutoML_20190901_021154_model_6,0.858252,0.595411,0.213311,0.407443,0.16601
DeepLearning_grid_1_AutoML_20190901_021154_model_1,0.855837,0.535754,0.21696,0.403427,0.162753
DeepLearning_grid_1_AutoML_20190901_021154_model_4,0.846207,1.77077,0.219216,0.450886,0.203298
GBM_grid_1_AutoML_20190901_021154_model_4,0.81969,0.680629,0.246071,0.493705,0.243745

In [9]:
aml.leader

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_grid_1_AutoML_20190901_021154_model_1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,114.0,114.0,38577.0,5.0,5.0,5.0,13.0,28.0,20.64035

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 0.12477055638268962
RMSE: 0.35322875928028513
LogLoss: 0.4229113640549777
Mean Per-Class Error: 0.11440528775366499
AUC: 0.9540742430062096
pr_auc: 0.9483626369348939
Gini: 0.9081484860124192

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.4963775245584766:

             No    Yes   Error             Rate
0     No  431.0   77.0  0.1516     (77.0/508.0)
1    Yes   38.0  454.0  0.0772     (38.0/492.0)
2  Total  469.0  531.0   0.115   (115.0/1000.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                        metric  threshold     value    idx
0                       max f1   0.496378  0.887586  210.0
1                       max f2   0.327950  0.931653  277.0
2                 max f0point5   0.601507  0.891509  147.0
3                 max accuracy   0.496378  0.885000  210.0
4                max precision   0.811268  1.000000    0.0
5                   max recall   0.265560  1.000000  318.0
6              max specificity   0.811268  1.000000    0.0
7             max absolute_mcc   0.496378  0.772577  210.0
8   max min_per_class_accuracy   0.528940  0.874016  194.0
9  max mean_per_class_accuracy   0.496378  0.885595  210.0

Gains/Lift Table: Avg response rate: 49.20 %, avg score: 49.30 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.01,0.794020,2.032520,2.032520,1.00,0.801274,1.000000,0.801274,0.020325,0.020325,103.252033,103.252033
1,,2,0.02,0.784843,2.032520,2.032520,1.00,0.788315,1.000000,0.794795,0.020325,0.040650,103.252033,103.252033
2,,3,0.03,0.779390,2.032520,2.032520,1.00,0.782757,1.000000,0.790782,0.020325,0.060976,103.252033,103.252033
3,,4,0.04,0.774630,2.032520,2.032520,1.00,0.777255,1.000000,0.787400,0.020325,0.081301,103.252033,103.252033
4,,5,0.05,0.770993,2.032520,2.032520,1.00,0.772813,1.000000,0.784483,0.020325,0.101626,103.252033,103.252033
5,,6,0.10,0.747404,2.032520,2.032520,1.00,0.757628,1.000000,0.771055,0.101626,0.203252,103.252033,103.252033
6,,7,0.15,0.733027,1.991870,2.018970,0.98,0.740791,0.993333,0.760967,0.099593,0.302846,99.186992,101.897019
7,,8,0.20,0.715940,1.910569,1.991870,0.94,0.724547,0.980000,0.751862,0.095528,0.398374,91.056911,99.186992
8,,9,0.30,0.676495,1.910569,1.964770,0.94,0.696952,0.966667,0.733559,0.191057,0.589431,91.056911,96.476965
9,,10,0.40,0.609068,1.666667,1.890244,0.82,0.650009,0.930000,0.712671,0.166667,0.756098,66.666667,89.024390
10,,11,0.50,0.519388,1.239837,1.760163,0.61,0.564966,0.866000,0.683130,0.123984,0.880081,23.983740,76.016260
11,,12,0.60,0.418213,0.853659,1.609079,0.42,0.479046,0.791667,0.649116,0.085366,0.965447,-14.634146,60.907859
12,,13,0.70,0.288589,0.304878,1.422764,0.15,0.338987,0.700000,0.604812,0.030488,0.995935,-69.512195,42.276423
13,,14,0.80,0.245336,0.040650,1.250000,0.02,0.265263,0.615000,0.562369,0.004065,1.000000,-95.934959,25.000000
14,,15,0.90,0.216349,0.000000,1.111111,0.00,0.229558,0.546667,0.525390,0.000000,1.000000,-100.000000,11.111111
15,,16,1.00,0.165961,0.000000,1.000000,0.00,0.201249,0.492000,0.492975,0.000000,1.000000,-100.000000,0.000000

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.14556802186627185
RMSE: 0.38153377552488305
LogLoss: 0.46851628326131584
Mean Per-Class Error: 0.16657064208437355
AUC: 0.9012867294027271
pr_auc: 0.8691349820569783
Gini: 0.8025734588054543

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.45140068955227786:

             No    Yes   Error             Rate
0     No  378.0  130.0  0.2559    (130.0/508.0)
1    Yes   38.0  454.0  0.0772     (38.0/492.0)
2  Total  416.0  584.0   0.168   (168.0/1000.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                        metric  threshold     value    idx
0                       max f1   0.451401  0.843866  229.0
1                       max f2   0.333867  0.909783  280.0
2                 max f0point5   0.587344  0.827952  151.0
3                 max accuracy   0.456377  0.832000  226.0
4                max precision   0.809301  1.000000    0.0
5                   max recall   0.204200  1.000000  378.0
6              max specificity   0.809301  1.000000    0.0
7             max absolute_mcc   0.451401  0.676387  229.0
8   max min_per_class_accuracy   0.522446  0.818898  187.0
9  max mean_per_class_accuracy   0.451401  0.833429  229.0

Gains/Lift Table: Avg response rate: 49.20 %, avg score: 49.16 %

,,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain
0,,1,0.01,0.788897,2.032520,2.032520,1.00,0.795967,1.000000,0.795967,0.020325,0.020325,103.252033,103.252033
1,,2,0.02,0.777000,1.829268,1.930894,0.90,0.784500,0.950000,0.790234,0.018293,0.038618,82.926829,93.089431
2,,3,0.03,0.773137,2.032520,1.964770,1.00,0.775281,0.966667,0.785249,0.020325,0.058943,103.252033,96.476965
3,,4,0.04,0.766121,1.626016,1.880081,0.80,0.770326,0.925000,0.781518,0.016260,0.075203,62.601626,88.008130
4,,5,0.05,0.763602,1.626016,1.829268,0.80,0.764683,0.900000,0.778151,0.016260,0.091463,62.601626,82.926829
5,,6,0.10,0.740924,1.869919,1.849593,0.92,0.751717,0.910000,0.764934,0.093496,0.184959,86.991870,84.959350
6,,7,0.15,0.723217,1.829268,1.842818,0.90,0.732069,0.906667,0.753979,0.091463,0.276423,82.926829,84.281843
7,,8,0.20,0.706660,1.788618,1.829268,0.88,0.715041,0.900000,0.744245,0.089431,0.365854,78.861789,82.926829
8,,9,0.30,0.667649,1.788618,1.815718,0.88,0.688942,0.893333,0.725810,0.178862,0.544715,78.861789,81.571816
9,,10,0.40,0.605309,1.544715,1.747967,0.76,0.641490,0.860000,0.704730,0.154472,0.699187,54.471545,74.796748
10,,11,0.50,0.519373,1.260163,1.650407,0.62,0.560898,0.812000,0.675964,0.126016,0.825203,26.016260,65.040650
11,,12,0.60,0.424640,1.077236,1.554878,0.53,0.479174,0.765000,0.643166,0.107724,0.932927,7.723577,55.487805
12,,13,0.70,0.297333,0.467480,1.399535,0.23,0.350149,0.688571,0.601306,0.046748,0.979675,-53.252033,39.953542
13,,14,0.80,0.252305,0.101626,1.237297,0.05,0.271996,0.608750,0.560142,0.010163,0.989837,-89.837398,23.729675
14,,15,0.90,0.217177,0.081301,1.108853,0.04,0.233029,0.545556,0.523796,0.008130,0.997967,-91.869919,10.885276
15,,16,1.00,0.163022,0.020325,1.000000,0.01,0.201446,0.492000,0.491561,0.002033,1.000000,-97.967480,0.000000

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.838,0.013509256,0.835,0.825,0.83,0.84,0.86
1,auc,0.90148556,0.015882747,0.8747499,0.9148,0.91066426,0.90016234,0.90705127
2,err,0.162,0.013509256,0.165,0.175,0.17,0.16,0.14
3,err_count,32.4,2.7018511,33.0,35.0,34.0,32.0,28.0
4,f0point5,0.8019787,0.022321627,0.80564785,0.78322786,0.7935154,0.78846157,0.8390411
5,f1,0.85232,0.014284243,0.8546255,0.8497854,0.8454546,0.8367347,0.875
6,f2,0.90976036,0.013647515,0.9099437,0.92870545,0.9046693,0.8913044,0.9141791
7,lift_top_group,2.039481,0.13757493,1.9607843,2.0,2.0408163,2.2727273,1.9230769
8,logloss,0.4685163,0.011569084,0.48844263,0.45995712,0.46436363,0.4682096,0.46160844
9,max_per_class_error,0.2742675,0.045720037,0.2857143,0.34,0.28431374,0.23214285,0.22916667
10,mcc,0.69617194,0.018258572,0.68694645,0.68857324,0.681223,0.6968529,0.727264
11,mean_per_class_accuracy,0.8392748,0.013292742,0.8326331,0.825,0.8323329,0.84983766,0.85657054
12,mean_per_class_error,0.16072516,0.013292742,0.16736695,0.175,0.16766706,0.15016234,0.14342949
13,mse,0.14556803,0.005216473,0.15451442,0.14172752,0.14378329,0.14554428,0.1422706
14,precision,0.77171636,0.027527897,0.776,0.7443609,0.76229507,0.7592593,0.81666666
15,r2,0.41574886,0.021118686,0.381695,0.4330899,0.4246367,0.40931705,0.4300056
16,recall,0.95281714,0.022091119,0.95098037,0.99,0.9489796,0.9318182,0.9423077
17,rmse,0.3814857,0.0067720376,0.3930832,0.37646717,0.37918767,0.38150266,0.37718776
18,specificity,0.7257325,0.045720037,0.71428573,0.66,0.71568626,0.76785713,0.7708333

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error
0,,2019-09-01 02:12:05,1.662 sec,0.0,0.499936,0.693019,0.500000,0.000000,1.00000,0.508
1,,2019-09-01 02:12:05,1.675 sec,5.0,0.487831,0.669088,0.939228,0.931347,2.03252,0.138
2,,2019-09-01 02:12:05,1.697 sec,10.0,0.477615,0.649295,0.943644,0.933534,2.03252,0.133
3,,2019-09-01 02:12:05,1.715 sec,15.0,0.469005,0.632871,0.941773,0.932278,2.03252,0.133
4,,2019-09-01 02:12:05,1.729 sec,20.0,0.460346,0.616575,0.944930,0.934036,2.03252,0.128
5,,2019-09-01 02:12:05,1.743 sec,25.0,0.449081,0.595668,0.946058,0.937687,2.03252,0.126
6,,2019-09-01 02:12:05,1.757 sec,30.0,0.439753,0.578568,0.947224,0.939484,2.03252,0.125
7,,2019-09-01 02:12:05,1.770 sec,35.0,0.431757,0.564035,0.947723,0.940540,2.03252,0.123
8,,2019-09-01 02:12:05,1.784 sec,40.0,0.426068,0.553738,0.947385,0.939622,2.03252,0.123
9,,2019-09-01 02:12:05,1.799 sec,45.0,0.417984,0.539210,0.947985,0.940590,2.03252,0.123
10,,2019-09-01 02:12:05,1.814 sec,50.0,0.412160,0.528783,0.949037,0.942223,2.03252,0.126
11,,2019-09-01 02:12:05,1.829 sec,55.0,0.405024,0.516066,0.950073,0.943424,2.03252,0.124
12,,2019-09-01 02:12:05,1.843 sec,60.0,0.399384,0.506007,0.950357,0.944186,2.03252,0.127
13,,2019-09-01 02:12:05,1.890 sec,65.0,0.393320,0.495188,0.950465,0.944588,2.03252,0.125
14,,2019-09-01 02:12:05,1.905 sec,70.0,0.389415,0.488188,0.950371,0.944144,2.03252,0.127
15,,2019-09-01 02:12:05,1.919 sec,75.0,0.384086,0.478672,0.950639,0.944495,2.03252,0.125
16,,2019-09-01 02:12:05,1.967 sec,80.0,0.379114,0.469806,0.951586,0.945711,2.03252,0.123
17,,2019-09-01 02:12:05,1.980 sec,85.0,0.375056,0.462545,0.951996,0.943967,2.03252,0.124
18,,2019-09-01 02:12:05,1.995 sec,90.0,0.370397,0.454181,0.952182,0.945692,2.03252,0.121
19,,2019-09-01 02:12:05,2.008 sec,95.0,0.365493,0.445330,0.952658,0.946295,2.03252,0.120

See the whole table with table.as_data_frame()

Variable Importances:

,variable,relative_importance,scaled_importance,percentage
0,work_interfere,3802.520020,1.000000,0.626285
1,family_history,648.182861,0.170461,0.106757
2,Country,376.036560,0.098891,0.061934
3,care_options,244.764343,0.064369,0.040313
4,no_employees,147.921051,0.038901,0.024363
5,leave,135.857483,0.035728,0.022376
6,benefits,125.955841,0.033124,0.020745
7,Gender,119.334000,0.031383,0.019655
8,mental_health_consequence,80.755318,0.021237,0.013301
9,obs_consequence,53.852493,0.014162,0.008870
10,Age_bin,49.778660,0.013091,0.008199
11,anonymity,48.667767,0.012799,0.008016
12,phys_health_interview,46.656651,0.012270,0.007684
13,coworkers,42.300343,0.011124,0.006967
14,supervisor,33.641983,0.008847,0.005541
15,seek_help,25.523558,0.006712,0.004204
16,mental_vs_physical,21.196833,0.005574,0.003491
17,remote_work,15.204746,0.003999,0.002504
18,wellness_program,14.557168,0.003828,0.002398
19,phys_health_consequence,13.234167,0.003480,0.002180

See the whole table with table.as_data_frame()

## Prediction

In [42]:

test = h2o.import_file('clean_final_T.csv',header=1)

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [43]:
test.columns

['s.no',
 'Gender',
 'Country',
 'self_employed',
 'family_history',
 'work_interfere',
 'no_employees',
 'remote_work',
 'tech_company',
 'benefits',
 'care_options',
 'wellness_program',
 'seek_help',
 'anonymity',
 'leave',
 'mental_health_consequence',
 'phys_health_consequence',
 'coworkers',
 'supervisor',
 'mental_health_interview',
 'phys_health_interview',
 'mental_vs_physical',
 'obs_consequence',
 'Age_bin']

In [38]:
preds = aml.predict(test)

gbm prediction progress: |████████████████████████████████████████████████| 100%

C:\Users\Vibhash-CRM\Anaconda3\lib\site-packages\h2o\job.py:70: UserWarning: Test/Validation dataset column 'Gender' has levels not trained on: [Cis Man]
  warnings.warn(w)
C:\Users\Vibhash-CRM\Anaconda3\lib\site-packages\h2o\job.py:70: UserWarning: Test/Validation dataset column 'Country' has levels not trained on: [China, Czech Republic, Georgia, Greece, Moldova, Philippines]
  warnings.warn(w)
C:\Users\Vibhash-CRM\Anaconda3\lib\site-packages\h2o\job.py:70: UserWarning: Test/Validation dataset column 'no_employees' has levels not trained on: [1-5, 6-25]
  warnings.warn(w)

In [44]:
final = pd.DataFrame(columns=["s.no","treatment"])
test_df = test.as_data_frame()
pred_df = preds.as_data_frame()
final["s.no"] = test_df["s.no"]
final["treatment"] = pred_df["predict"]
final.to_csv("solution_h2O_final.csv",index=False)